version: 2.1
# jobs:
#   build:
#     working_directory: ~/repo
#     docker:
#       - image: circleci/python:3.6.1
#     steps:
#       - checkout
#       - restore_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "scripts/requirements.txt" }}
#       - run:
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             pip install -r scripts/requirements.txt
#       - save_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "scripts/requirements.txt" }}
#           paths:
#             - "venv"
#       - run:
#           command: |
#             . venv/bin/activate
#             cd scripts
#             nosetests

jobs:
  build_and_publish_grch37_mutationassessor:
    docker:
      - image: cimg/go:1.17
    # large is the best image for free tier users
    resource_class: large 
    steps:
      - checkout
      # ... steps for building/testing app ...
      - run:
          name: Get Git tag
          command: |
            git fetch --tags
            echo 'export GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) | sed 's/^v//g')' >> "$BASH_ENV"
            source "$BASH_ENV"
            echo $GIT_TAG
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=${GIT_TAG}_mutationassessor
          IMAGE=leexdocker/gn-mongodb
          echo ${CIRCLE_BRANCH} && echo ${GIT_TAG} && echo ${DOCKER_PASSWORD} && echo ${DOCKER_USERNAME}
          docker build -t $IMAGE:$TAG --build-arg MUTATIONASSESSOR=false .
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
          docker push $IMAGE:$TAG

workflows:
  build:
    jobs:
      - build_and_publish_grch37_mutationassessor:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /.*/


# workflows:
#   version: 2
#   build_and_publish_grch37_mutationassessor:
#     jobs:
#       - docker/publish:
#           executor: ubuntu
#           image: leexdocker/gn-mongodb
#           tag: ${CIRCLE_TAG}_mutationassessor
#           extra_build_args: '--build-arg MUTATIONASSESSOR=false'
#           username: ${DOCKER_USERNAME}
#           password: ${DOCKER_PASSWORD}
#           filters:
#             branches:
#               only: /.*/
#             tags:
#               only: /.*/